blocks/header/header.js

This PR is an attempt to fix the header loading. Please @kmurugulla let me know if it is the same tweak you had in mind.
Fix #3 
Test URLs:
- After: https://3-header--durysta--hlxsites.hlx.page

issues-3: Fix header.js to load header

---

blocks/footer/footer.css
styles/styles.css

Fix #4
Test URLs:
- After: https://4-footer--durysta--hlxsites.hlx.page/

issues-4: Add footer style

---

blocks/header/header.css
blocks/header/header.js
styles/styles.css

This PR introduces the menu style. Animation will come in a follow-up PR.
Part of #3 
Tested with #16
Test URLs:
- After: https://3-header--durysta--hlxsites.hlx.page/

issues-3: Add menu style

---

blocks/columns/columns.css
blocks/columns/columns.js

Can be controlled with section metadata:
- "style: columns-slide-image-from-right"
- "style: columns-slide-image-from-left"
Test URLs:
- After: https://rootpeadev--durysta--hlxsites.hlx.page/drafts/rootpea/

Image animation in sections

---

scripts/delayed.js

Fix #23 
Fix #22  
Test URLs:
- After: https://23-cookie--durysta--hlxsites.hlx.page

adding cookie consent open functionality and loading adobe launch script

---

scripts/scripts.js

Fix #31 
Test URLs:
- After: https://31-heroauto--durysta--hlxsites.hlx.page

removing buildHero auto block

---

blocks/header/header.js
scripts/scripts.js

Fix #33 
Test URLs:
- After: https://33-linkimages--durysta--hlxsites.hlx.page/

adding link pictures methods . image followed by hyperlink in the doc

---

blocks/carousel/carousel.css
blocks/header/header.css
styles/styles.css

Fix #35 
Test URLs:
- After: https://35-fix-nav--durysta--hlxsites.hlx.page/

35 fix nav

---

styles/styles.css

Fix #43
Test URLs:
- After: https://43-sectiondivider--durysta--hlxsites.hlx.page

section divider increase the border size to 10px

---

blocks/footer/footer.css

Fix #50
Test URLs:
- After: https://50-footersize--durysta--hlxsites.hlx.page

footer size

---

blocks/header/header.css
styles/styles.css

Fix #40
Test URLs:
- After: https://40-adjustnavheight--durysta--hlxsites.hlx.page

adjust nav height #40

---

blocks/columns/columns.css
blocks/faq/faq.css

Fix #47
Test URLs:
- After: https://47-resourcesfaqsectionstyling--durysta--hlxsites.hlx.page

resources , faq section styling #47

---

blocks/fragment/fragment.css
blocks/fragment/fragment.js
styles/styles.css

Fix #9 
Test URLs:
- After: https://9-isi-fragment--durysta--hlxsites.hlx.page/find-a-doctor
Changes from PR #51 also affect styling of the ISI fragment

9 isi fragment

---

blocks/columns/columns.css
blocks/columns/columns.js
styles/styles.css

Fix #36
Fix #48
Test URLs:
- After: https://36-textstyling--durysta--hlxsites.hlx.page

durysta may be right for you section #48 and Text styling for columns blocks #36

---

blocks/columns/columns.css

Fix #27
Test URLs:
- After: https://27-imageoverflow--durysta--hlxsites.hlx.page

add overflow hidden for image animations to prevent horizontal scrollbars

---

blocks/columns/columns.css
styles/styles.css

Fix #48
Fix #58 
Test URLs:
- After: https://48-separator--durysta--hlxsites.hlx.page/drafts/rootpea/

48 separator, list items, text styling, image sizes, spacing, tablet layout

---

blocks/isi/isi.css
blocks/isi/isi.js
scripts/set-attributes.js
styles/styles.css

Fix #12 
Test URLs:
- After: https://12-safety-information-floater--durysta--hlxsites.hlx.page
Notes:
- Bold text at the end of the expander will be addressed in a different PR by using global `strong` styles.

12 safety information floater

---

blocks/header/header.css
blocks/header/header.js

Fix #45
Test URLs:
- After: https://45-headersectionhighlighter--durysta--hlxsites.hlx.page

header - in page section highlighter

---

.prettierrc
blocks/carousel/carousel.css
blocks/carousel/carousel.js
styles/styles.css

Fix #41
Test URLs:
- After: https://41-hero-carousel-styling--durysta--hlxsites.hlx.page/
Notes: this merge also fixes the styles for the green-box carousel.

41 hero carousel styling

---

blocks/columns/columns.css
styles/styles.css

Set default bold font to minimize number of overrides:
- Bolded text font Default: ITC Avant Garde Gothic W01 Bd
- Default for Columns: ITC Avant Garde Gothic W01 Md
+ minor cleanup for sliding images
Fix #55
Test URLs:
- After: https://55-default-bold-font--durysta--hlxsites.hlx.page

55 default bold font

---

blocks/columns/columns.css
scripts/lib-franklin.js
styles/styles.css

Fix #44
Test URLs:
- After: https://44-about-durysta-spacing--durysta--hlxsites.hlx.page

44 about durysta spacing

---

styles/styles.css

Fix #44
Test URLs:
- After: https://44-listitem--durysta--hlxsites.hlx.page

list item margin only in main section, not in header/nav

---

blocks/columns/columns.css

Fix #48
Test URLs:
- After: https://48-separator-2--durysta--hlxsites.hlx.page

fix separator size on tablet+ and adjust margins on columns mobile

---

README.md
blocks/carousel/carousel.css
blocks/footer/footer.css
blocks/header/header.css
styles/styles.css

Additional suggestions added for read me, and styles to improve consistency
Fix #42 
Test URLs:
- After: https://42-glucoma-simulator-styling--durysta--hlxsites.hlx.page/

42 glucoma simulator styling

---

blocks/carousel/carousel.css
blocks/faq/faq.css
styles/styles.css

Fix #80 
Test URLs:
- After: https://80-spacing--durysta--hlxsites.hlx.page

Spacing below green-box and faq sections #80

---

scripts/delayed.js

Fix #22 
Test URLs:
- After: https://22-adobelaunch--durysta--hlxsites.hlx.page

adding dev version of adobe launch script on franklin preview and live

---

tools/sidekick/config.json
tools/sidekick/library.html

Fix #18 
Test URLs:
- Before: https://main--durysta--hlxsites.hlx.page/tools/sidekick/library.html?plugin=blocks
- After: https://18-configure-library-sidekick-plugin--durysta--hlxsites.hlx.page/tools/sidekick/library.html?plugin=blocks

Initial sidekick library configuration

---

scripts/scripts.js
styles/styles.css

Fix #73
Test URLs:
- After: https://73-fine-tune-video-fade--durysta--hlxsites.hlx.page

73 - fine tune video fade animation

---

scripts/scripts.js

Fix #93
Test URLs:
- After: https://93-click-image--durysta--hlxsites.hlx.page/drafts/rootpea/draft

93 image links

---

scripts/scripts.js
styles/styles.css

Fix #92
Test URLs:
- After: https://92-video-playback-reopen--durysta--hlxsites.hlx.page

92 video playback continue on reopen

---

scripts/scripts.js
styles/styles.css

Fix #91
Test URLs:
- After: https://91-video-pre-load--durysta--hlxsites.hlx.page

91 preload videos before opening the modal
